#!/usr/bin/env python3
# Generates rvv_ldst.c: RVV unit-stride vle/vse differential test.
import itertools

LMULS = [('mf8', -3), ('mf4', -2), ('mf2', -1), ('m1', 0), ('m2', 1), ('m4', 2), ('m8', 3)]
SEWS = [8, 16, 32, 64]
EEWS = [8, 16, 32, 64]
lg = {8: 0, 16: 1, 32: 2, 64: 3}

combos = []
for eew in EEWS:
    for sew in SEWS:
        for lname, l in LMULS:
            # valid vtype for ELEN=64: fractional LMUL needs SEW <= ELEN * LMUL
            if l < 0 and sew > (64 >> -l):
                continue
            emul = lg[eew] - lg[sew] + l
            if emul < -3 or emul > 3:
                continue
            combos.append((eew, sew, lname, l, emul))

out = []
w = out.append
w('''/* generated by gen_ldst.py: vle<eew>.v / vse<eew>.v for every valid
 * EEW/SEW/LMUL, masked or not, several vl, plus page-boundary cases */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <signal.h>
#include <setjmp.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>

static uint8_t init[8 * 64] __attribute__((aligned(64)));
static uint8_t outv[8 * 64] __attribute__((aligned(64)));
static uint8_t maskbuf[64] __attribute__((aligned(64)));
static uint8_t *page;           /* 2 pages: RW then PROT_NONE */
static long pgsz, vlenb;
static uint64_t h, hall;

static int dump;
static void mix(const void *p, size_t n)
{
    const uint8_t *b = p;
    for (size_t i = 0; i < n; i++) {
        h = (h ^ b[i]) * 0x100000001b3ull;
    }
    if (dump) {
        for (size_t i = 0; i < n; i++) {
            printf("%02x", b[i]);
        }
        printf("\\n");
    }
}

static uint64_t rnd = 0x9e3779b97f4a7c15ull;
static uint64_t next(void)
{
    rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17;
    return rnd;
}
static void fill(uint8_t *p, size_t n)
{
    for (size_t i = 0; i < n; i++) {
        p[i] = next();
    }
}
''')

for (eew, sew, lname, l, emul) in combos:
    for masked in (0, 1):
        vm = ', v0.t' if masked else ''
        nm = f'e{eew}_s{sew}_{lname}_{"m" if masked else "u"}'
        w(f'''
static long ld_{nm}(long avl, const void *src)
{{
    long vl;
    asm volatile("vl8re8.v v8, (%[init])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "vsetvli %[vl], %[avl], e{sew}, {lname}, tu, mu\\n\\t"
                 "vle{eew}.v v8, (%[src]){vm}\\n\\t"
                 "vs8r.v v8, (%[out])\\n\\t"
                 : [vl] "=&r"(vl)
                 : [init] "r"(init), [mb] "r"(maskbuf), [avl] "r"(avl),
                   [src] "r"(src), [out] "r"(outv)
                 : "memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13",
                   "v14", "v15");
    return vl;
}}

static long st_{nm}(long avl, void *dst)
{{
    long vl;
    asm volatile("vl8re8.v v8, (%[init])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "vsetvli %[vl], %[avl], e{sew}, {lname}, tu, mu\\n\\t"
                 "vse{eew}.v v8, (%[dst]){vm}\\n\\t"
                 : [vl] "=&r"(vl)
                 : [init] "r"(init), [mb] "r"(maskbuf), [avl] "r"(avl),
                   [dst] "r"(dst)
                 : "memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13",
                   "v14", "v15");
    return vl;
}}
''')

KS = [1, 3, 4, 8, 13, 16, 31]
for (eew, sew, lname, l, emul) in combos:
    for masked in (0, 1):
        vm = ', v0.t' if masked else ''
        for k in KS:
            nm = f'i{k}_e{eew}_s{sew}_{lname}_{"m" if masked else "u"}'
            w(f'''
static long ld_{nm}(long avl, const void *src)
{{
    long vl;
    asm volatile("vl8re8.v v8, (%[init])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "vsetivli %[vl], {k}, e{sew}, {lname}, tu, mu\\n\\t"
                 "vle{eew}.v v8, (%[src]){vm}\\n\\t"
                 "vs8r.v v8, (%[out])\\n\\t"
                 : [vl] "=&r"(vl)
                 : [init] "r"(init), [mb] "r"(maskbuf),
                   [src] "r"(src), [out] "r"(outv)
                 : "memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13",
                   "v14", "v15");
    return vl;
}}

static long st_{nm}(long avl, void *dst)
{{
    long vl;
    asm volatile("vl8re8.v v8, (%[init])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "vsetivli %[vl], {k}, e{sew}, {lname}, tu, mu\\n\\t"
                 "vse{eew}.v v8, (%[dst]){vm}\\n\\t"
                 "lb %[vl], 0(%[dst])\\n\\t"
                 "csrr %[vl], vl\\n\\t"
                 : [vl] "=&r"(vl)
                 : [init] "r"(init), [mb] "r"(maskbuf),
                   [dst] "r"(dst)
                 : "memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13",
                   "v14", "v15");
    return vl;
}}
''')

w('''
typedef long (*tfn)(long, void *);
struct tcase { const char *name; tfn ld, st; int eew, sew, lmul, emul, masked, imm; };
static const struct tcase cases[] = {
''')
for (eew, sew, lname, l, emul) in combos:
    for masked in (0, 1):
        nm = f'e{eew}_s{sew}_{lname}_{"m" if masked else "u"}'
        w(f'    {{ "{nm}", (tfn)ld_{nm}, (tfn)st_{nm}, {eew}, {sew}, {l}, {emul}, {masked}, 0 }},\n')
for (eew, sew, lname, l, emul) in combos:
    for masked in (0, 1):
        for k in KS:
            nm = f'i{k}_e{eew}_s{sew}_{lname}_{"m" if masked else "u"}'
            w(f'    {{ "{nm}", (tfn)ld_{nm}, (tfn)st_{nm}, {eew}, {sew}, {l}, {emul}, {masked}, {k} }},\n')
w('''};
#define NCASES (sizeof(cases) / sizeof(cases[0]))

static sigjmp_buf jb;
static volatile long fault_off;
static void segv(int sig, siginfo_t *si, void *uc)
{
    fault_off = (uint8_t *)si->si_addr - (page + pgsz);
    siglongjmp(jb, 1);
}

static void reset_vstart(void)
{
    asm volatile("csrw vstart, zero" ::: "memory");
}

int main(int argc, char **argv)
{
    uint8_t *buf;
    struct sigaction sa;

    asm volatile("csrr %0, vlenb" : "=r"(vlenb));
    pgsz = sysconf(_SC_PAGESIZE);
    page = mmap(NULL, 2 * pgsz, PROT_READ | PROT_WRITE,
                MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    mprotect(page + pgsz, pgsz, PROT_NONE);
    buf = malloc(8 * 64 + 256);
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = segv;
    sa.sa_flags = SA_SIGINFO | SA_NODEFER;
    sigaction(SIGSEGV, &sa, NULL);
    printf("vlenb %ld, %zu cases\\n", vlenb, NCASES);

    for (size_t c = 0; c < NCASES; c++) {
        const struct tcase *t = &cases[c];
        long vlmax = t->lmul >= 0 ? (vlenb * 8 / t->sew) << t->lmul
                                  : (vlenb * 8 / t->sew) >> -t->lmul;
        long avls[] = { 0, 1, 2, 3, vlmax / 2, vlmax - 1, vlmax, vlmax + 1,
                        1000000, -1 };
        long ebytes = t->eew / 8;
        h = 0xcbf29ce484222325ull;
        dump = getenv("RVT_DUMP") && !strcmp(getenv("RVT_DUMP"), t->name);
        for (int k = 0; k < (t->imm ? 1 : 10); k++) {
            for (int rep = 0; rep < 3; rep++) {
                long avl = avls[k], vl, misal = rep == 2 ? 3 : 0;
                uint8_t *src = buf + 64 + misal;
                fill(init, sizeof(init));
                fill(maskbuf, sizeof(maskbuf));
                fill(buf, 8 * 64 + 256);
                vl = t->ld(avl, src);
                mix(&vl, sizeof(vl));
                mix(outv, 8 * vlenb);
                fill(init, sizeof(init));
                vl = t->st(avl, src);
                mix(&vl, sizeof(vl));
                mix(buf, 8 * 64 + 256);
            }
        }

        /* after the fault tests of the previous case, which may or may not
           have written the elements before the faulting one */
        memset(page, 0x5a, pgsz);

        /* the active elements end at the page boundary: no fault */
        for (long vl = t->imm ? (t->imm < vlmax ? t->imm : vlmax) : 0;
             vl <= vlmax && vl <= 64 && (!t->imm || vl == (t->imm < vlmax ? t->imm : vlmax)); vl++) {
            uint8_t *src = page + pgsz - vl * ebytes;
            long got;
            fill(init, sizeof(init));
            fill(maskbuf, sizeof(maskbuf));
            fault_off = -999999;
            if (sigsetjmp(jb, 1) == 0) {
                got = t->ld(vl, src);
                mix(&got, sizeof(got));
                mix(outv, 8 * vlenb);
                got = t->st(vl, src);
                mix(&got, sizeof(got));
                mix(page + pgsz - 8 * 64, 8 * 64);
            } else {
                reset_vstart();
                printf("%s: unexpected fault vl %ld at %+ld\\n", t->name, vl,
                       fault_off);
            }
        }

        /* masked: active elements before the boundary, the others past it */
        if (t->masked && !t->imm) {
            for (long split = 0; split < vlmax && split <= 64; split++) {
                uint8_t *src = page + pgsz - split * ebytes;
                long got;
                fill(init, sizeof(init));
                memset(maskbuf, 0, sizeof(maskbuf));
                for (long i = 0; i < split; i++) {
                    if (next() & 1) {
                        maskbuf[i / 8] |= 1 << (i % 8);
                    }
                }
                if (sigsetjmp(jb, 1) == 0) {
                    got = t->ld(vlmax, src);
                    mix(&got, sizeof(got));
                    mix(outv, 8 * vlenb);
                    got = t->st(vlmax, src);
                    mix(&got, sizeof(got));
                    mix(page + pgsz - 8 * 64, 8 * 64);
                } else {
                    reset_vstart();
                    printf("%s: unexpected fault split %ld at %+ld\\n",
                           t->name, split, fault_off);
                }
            }
        }

        /* one active element past the boundary: fault (contents not
           compared, they may differ in how far the access got) */
        for (int st = 0; st < 2; st++) {
            long vl = t->imm ? (t->imm < vlmax ? t->imm : vlmax) : vlmax < 5 ? vlmax : 5;
            uint8_t *src;
            if (vl == 0) {
                continue;
            }
            src = page + pgsz - (vl - 1) * ebytes;
            memset(maskbuf, 0xff, sizeof(maskbuf));
            fault_off = -999999;
            if (sigsetjmp(jb, 1) == 0) {
                if (st) {
                    t->st(vl, src);
                } else {
                    t->ld(vl, src);
                }
                printf("%s: %s did not fault\\n", t->name, st ? "st" : "ld");
            } else {
                reset_vstart();
                if (fault_off < 0 || fault_off >= ebytes) {
                    printf("%s: %s fault at %+ld\\n", t->name,
                           st ? "st" : "ld", fault_off);
                }
            }
        }
        printf("%-16s %016llx\\n", t->name, (unsigned long long)h);
        hall ^= h + c;
    }
    printf("all %016llx\\n", (unsigned long long)hall);
    return 0;
}
''')
open('rvv_ldst.c', 'w').write(''.join(out))
print(len(combos), 'combos')
