#!/usr/bin/env python3
# Generates rvfp.c: differential test of the RISC-V F and D instructions,
# every rounding mode (static, and dynamic with each frm), results and fflags.
RMS = ['rne', 'rtz', 'rdn', 'rup', 'rmm', 'dyn']
out = []
w = out.append
w(r'''/* generated by gen_fp.py */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

typedef struct { uint64_t r; uint64_t fl; } res_t;
static uint64_t h;
static int dump;
static void mix(uint64_t v)
{
    for (int i = 0; i < 8; i++) {
        h = (h ^ ((v >> (8 * i)) & 0xff)) * 0x100000001b3ull;
    }
}
static void rec(const char *n, uint64_t a, uint64_t b, uint64_t c, res_t r)
{
    mix(r.r);
    mix(r.fl);
    if (dump) {
        printf("%s %016llx %016llx %016llx -> %016llx %02llx\n", n,
               (unsigned long long)a, (unsigned long long)b,
               (unsigned long long)c, (unsigned long long)r.r,
               (unsigned long long)r.fl);
    }
}
static uint64_t rnd = 0x2545f4914f6cdd1dull;
static uint64_t next(void)
{
    rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17;
    return rnd;
}
''')

def fn(name, body, args):
    w('static res_t %s(%s)\n{\n    res_t r;\n    asm volatile(%s\n' % (name, ', '.join('uint64_t %s' % a for a in args), body))
    w('        : "=&r"(r.r), "=&r"(r.fl)\n        : %s\n        : "fa0", "fa1", "fa2", "fa3", "t0", "memory");\n    return r;\n}\n' %
      ', '.join('"r"(%s)' % a for a in args))

tests = []   # (cname, kind, prec_in)
# kind: f2 (fp,fp->fp), f1, f3, cmp (fp,fp->int), cvti (fp->int), cvtf (int->fp), cvfmt
for p in ['s', 'd']:
    for op in ['fadd', 'fsub', 'fmul', 'fdiv']:
        for rm in RMS:
            n = '%s_%s_%s' % (op, p, rm)
            fn(n, '"fmv.d.x fa0, %%2\\n\\tfmv.d.x fa1, %%3\\n\\tfsflags zero\\n\\t%s.%s fa2, fa0, fa1, %s\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % (op, p, rm), ['a', 'b'])
            tests.append((n, 'f2', p))
    for rm in RMS:
        n = 'fsqrt_%s_%s' % (p, rm)
        fn(n, '"fmv.d.x fa0, %%2\\n\\tfsflags zero\\n\\tfsqrt.%s fa2, fa0, %s\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % (p, rm), ['a'])
        tests.append((n, 'f1', p))
    for op in ['fmadd', 'fmsub', 'fnmsub', 'fnmadd']:
        for rm in RMS:
            n = '%s_%s_%s' % (op, p, rm)
            fn(n, '"fmv.d.x fa0, %%2\\n\\tfmv.d.x fa1, %%3\\n\\tfmv.d.x fa3, %%4\\n\\tfsflags zero\\n\\t%s.%s fa2, fa0, fa1, fa3, %s\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % (op, p, rm), ['a', 'b', 'c'])
            tests.append((n, 'f3', p))
    for op in ['fmin', 'fmax']:
        n = '%s_%s' % (op, p)
        fn(n, '"fmv.d.x fa0, %%2\\n\\tfmv.d.x fa1, %%3\\n\\tfsflags zero\\n\\t%s.%s fa2, fa0, fa1\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % (op, p), ['a', 'b'])
        tests.append((n, 'f2', p))
    for op in ['feq', 'flt', 'fle']:
        n = '%s_%s' % (op, p)
        fn(n, '"fmv.d.x fa0, %%2\\n\\tfmv.d.x fa1, %%3\\n\\tfsflags zero\\n\\t%s.%s %%0, fa0, fa1\\n\\tfrflags %%1\\n\\t"' % (op, p), ['a', 'b'])
        tests.append((n, 'cmp', p))
    for it in ['w', 'wu', 'l', 'lu']:
        for rm in RMS:
            n = 'fcvt_%s_%s_%s' % (it, p, rm)
            fn(n, '"fmv.d.x fa0, %%2\\n\\tfsflags zero\\n\\tfcvt.%s.%s %%0, fa0, %s\\n\\tfrflags %%1\\n\\t"' % (it, p, rm), ['a'])
            tests.append((n, 'cvti', p))
            n = 'fcvt_%s_%s_%s' % (p, it, rm)
            rmn = {'rne': 0, 'rtz': 1, 'rdn': 2, 'rup': 3, 'rmm': 4, 'dyn': 7}[rm]
            f7 = 0x68 if p == 's' else 0x69
            rs2 = {'w': 'x0', 'wu': 'x1', 'l': 'x2', 'lu': 'x3'}[it]
            fn(n, '"fsflags zero\\n\\t.insn r 0x53, %d, %d, fa2, %%2, %s\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % (rmn, f7, rs2), ['a'])
            tests.append((n, 'cvtf', p))
for rm in RMS:
    n = 'fcvt_s_d_%s' % rm
    fn(n, '"fmv.d.x fa0, %%2\\n\\tfsflags zero\\n\\tfcvt.s.d fa2, fa0, %s\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % rm, ['a'])
    tests.append((n, 'f1', 'd'))
    n = 'fcvt_d_s_%s' % rm
    rmn = {'rne': 0, 'rtz': 1, 'rdn': 2, 'rup': 3, 'rmm': 4, 'dyn': 7}[rm]
    fn(n, '"fmv.d.x fa0, %%2\\n\\tfsflags zero\\n\\t.insn r 0x53, %d, 0x21, fa2, fa0, x0\\n\\tfrflags %%1\\n\\tfmv.x.d %%0, fa2\\n\\t"' % rmn, ['a'])
    tests.append((n, 'f1', 's'))

w(r'''
/* special operands */
static const uint64_t dspec[] = {
    0x0000000000000000ull, 0x8000000000000000ull, 0x3ff0000000000000ull,
    0xbff0000000000000ull, 0x7ff0000000000000ull, 0xfff0000000000000ull,
    0x7ff8000000000000ull, 0xfff8000000000000ull, 0x7ff0000000000001ull,
    0xfff4000000000123ull, 0x7ff8000000000456ull, 0x0000000000000001ull,
    0x800fffffffffffffull, 0x0010000000000000ull, 0x8010000000000000ull,
    0x000fffffffffffffull, 0x7fefffffffffffffull, 0xffefffffffffffffull,
    0x4000000000000000ull, 0x3fe0000000000000ull, 0xbfe0000000000000ull,
    0x3ff8000000000000ull, 0x4004000000000000ull, 0xbfe3333333333333ull,
    0x41dfffffffc00000ull, 0x41dfffffffe00000ull, 0x41e0000000000000ull,
    0xc1e0000000000000ull, 0xc1e0000000200000ull, 0x41efffffffe00000ull,
    0x41f0000000000000ull, 0x43e0000000000000ull, 0xc3e0000000000000ull,
    0x43f0000000000000ull, 0x43dfffffffffffffull, 0x3ca0000000000000ull,
    0x0010000000000001ull, 0x3fefffffffffffffull, 0x4340000000000001ull,
    0x3ff0000000000001ull, 0xc00921fb54442d18ull, 0x3fd5555555555555ull,
};
static const uint32_t sspec[] = {
    0x00000000, 0x80000000, 0x3f800000, 0xbf800000, 0x7f800000, 0xff800000,
    0x7fc00000, 0xffc00000, 0x7f800001, 0xffa00123, 0x7fc00456, 0x00000001,
    0x807fffff, 0x00800000, 0x80800000, 0x007fffff, 0x7f7fffff, 0xff7fffff,
    0x40000000, 0x3f000000, 0xbf000000, 0x3fc00000, 0x40200000, 0xbf19999a,
    0x4effffff, 0x4f000000, 0xcf000000, 0xcf000001, 0x4f7fffff, 0x4f800000,
    0x5f000000, 0xdf000000, 0x5f800000, 0x5effffff, 0x33800000, 0x00800001,
    0x3f7fffff, 0x4b800001, 0x3f800001, 0xc0490fdb, 0x3eaaaaab,
};
static const uint64_t ispec[] = {
    0, 1, (uint64_t)-1, 0x7fffffff, 0x80000000, 0xffffffff80000000ull,
    0xffffffff, 0x100000000ull, 0x7fffffffffffffffull, 0x8000000000000000ull,
    0xffffffffffffffffull, 0x1000001, 0x1000003, 0x20000000000001ull,
    0x20000000000003ull, 0xfffffffffeffffffull, 0x123456789abcdefull,
    0xfedcba9876543210ull, 1000000, (uint64_t)-1000000,
};
#define ND (sizeof(dspec) / 8)
#define NS (sizeof(sspec) / 4)
#define NI (sizeof(ispec) / 8)

/* an operand: specials and random values; for binary32 NaN-boxed, but
   now and then not (then it is the default NaN) */
static uint64_t opnd(char p, unsigned i)
{
    if (p == 'd') {
        if (i < ND) {
            return dspec[i];
        }
        switch (next() & 3) {
        case 0: return next();
        case 1: return (next() & 0x800fffffffffffffull) | (0x3fcull + (next() % 16)) << 52;
        case 2: return next() & 0x801fffffffffffffull;
        default: return (next() & 0x800fffffffffffffull) | 0x7fe0000000000000ull;
        }
    } else {
        uint64_t v;
        if (i < NS) {
            v = sspec[i];
        } else {
            switch (next() & 3) {
            case 0: v = (uint32_t)next(); break;
            case 1: v = ((uint32_t)next() & 0x807fffff) | (uint32_t)(0x7c + next() % 8) << 23; break;
            case 2: v = (uint32_t)next() & 0x80ffffff; break;
            default: v = ((uint32_t)next() & 0x807fffff) | 0x7f000000; break;
            }
        }
        if ((next() & 63) == 0) {
            return v | ((next() & 0xffffffff) << 32);      /* not NaN-boxed */
        }
        return v | 0xffffffff00000000ull;
    }
}
static uint64_t iopnd(unsigned i)
{
    if (i < NI) {
        return ispec[i];
    }
    switch (next() & 3) {
    case 0: return next();
    case 1: return (int64_t)(int32_t)next();
    case 2: return next() >> (next() % 64);
    default: return -(next() >> (next() % 64));
    }
}

typedef res_t (*f1_t)(uint64_t);
typedef res_t (*f2_t)(uint64_t, uint64_t);
typedef res_t (*f3_t)(uint64_t, uint64_t, uint64_t);
struct test { const char *name; int kind; char p; void *fn; };
enum { F1, F2, F3, CMP, CVTI, CVTF };
static const struct test tests[] = {
''')
kinds = {'f1': 'F1', 'f2': 'F2', 'f3': 'F3', 'cmp': 'CMP', 'cvti': 'CVTI', 'cvtf': 'CVTF'}
for (n, k, p) in tests:
    w('    { "%s", %s, \'%s\', (void *)%s },\n' % (n, kinds[k], p, n))
w(r'''};
#define NT (sizeof(tests) / sizeof(tests[0]))

int main(int argc, char **argv)
{
    const char *d = getenv("RVFP_DUMP");
    uint64_t all = 0;

    for (size_t t = 0; t < NT; t++) {
        const struct test *x = &tests[t];
        int dyn = strstr(x->name, "_dyn") != NULL || strncmp(x->name, "fmin", 4) == 0
                  || strncmp(x->name, "fmax", 4) == 0 || x->kind == CMP;
        dump = d && !strcmp(d, x->name);
        h = 0xcbf29ce484222325ull;
        for (int frm = 0; frm < (dyn ? 5 : 1); frm++) {
            unsigned nsp = x->p == 'd' ? ND : NS;
            asm volatile("fsrm %0" : : "r"(frm));
            if (x->kind == F1 || x->kind == CVTI) {
                for (unsigned i = 0; i < nsp + 3000; i++) {
                    uint64_t a = opnd(x->p, i);
                    rec(x->name, a, 0, frm, ((f1_t)x->fn)(a));
                }
            } else if (x->kind == CVTF) {
                for (unsigned i = 0; i < NI + 3000; i++) {
                    uint64_t a = iopnd(i);
                    rec(x->name, a, 0, frm, ((f1_t)x->fn)(a));
                }
            } else if (x->kind == F2 || x->kind == CMP) {
                for (unsigned i = 0; i < nsp; i++) {
                    for (unsigned j = 0; j < nsp; j++) {
                        uint64_t a = opnd(x->p, i), b = opnd(x->p, j);
                        rec(x->name, a, b, frm, ((f2_t)x->fn)(a, b));
                    }
                }
                for (unsigned i = 0; i < 4000; i++) {
                    uint64_t a = opnd(x->p, 1000), b = opnd(x->p, 1000);
                    rec(x->name, a, b, frm, ((f2_t)x->fn)(a, b));
                }
            } else {
                for (unsigned i = 0; i < 18; i++) {
                    for (unsigned j = 0; j < 18; j++) {
                        for (unsigned k = 0; k < 18; k++) {
                            uint64_t a = opnd(x->p, i), b = opnd(x->p, j);
                            uint64_t c = opnd(x->p, k);
                            rec(x->name, a, b, c, ((f3_t)x->fn)(a, b, c));
                        }
                    }
                }
                for (unsigned i = 0; i < 6000; i++) {
                    uint64_t a = opnd(x->p, 1000), b = opnd(x->p, 1000);
                    uint64_t c = opnd(x->p, 1000);
                    if (i & 1) {
                        /* a * 1 - a: exact cancellation, signed zeros */
                        b = x->p == 'd' ? 0x3ff0000000000000ull
                                        : 0xffffffff3f800000ull;
                        c = a ^ (x->p == 'd' ? 0x8000000000000000ull
                                             : 0x80000000ull);
                    }
                    rec(x->name, a, b, c, ((f3_t)x->fn)(a, b, c));
                }
            }
        }
        asm volatile("fsrm zero");
        printf("%-18s %016llx\n", x->name, (unsigned long long)h);
        all = all * 31 + h;
    }
    printf("all %016llx\n", (unsigned long long)all);
    return 0;
}
''')
open('rvfp.c', 'w').write(''.join(out))
print(len(tests), 'tests')
