#!/usr/bin/env python3
# Generates rvv_ldff.c: RVV fault-only-first loads (vle<eew>ff.v)
# differential test: every EEW/SEW/LMUL, masked or not, vl from a register
# or known (vsetivli), the elements inside one page or reaching the next
# (PROT_NONE) one, vl = 0, a fault on the first element; followed in the
# same TB by csrr vl and vse<eew>.v (which use vl), plus a strlen loop.

LMULS = [('mf8', -3), ('mf4', -2), ('mf2', -1), ('m1', 0), ('m2', 1), ('m4', 2), ('m8', 3)]
SEWS = [8, 16, 32, 64]
EEWS = [8, 16, 32, 64]
lg = {8: 0, 16: 1, 32: 2, 64: 3}

combos = []
for eew in EEWS:
    for sew in SEWS:
        for lname, l in LMULS:
            if l < 0 and sew > (64 >> -l):
                continue
            emul = lg[eew] - lg[sew] + l
            if emul < -3 or emul > 3:
                continue
            combos.append((eew, sew, lname, l, emul))

KS = [0, 1, 3, 8, 13, 16, 31]

out = []
w = out.append
w('''/* generated by gen_ldff.py */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <signal.h>
#include <setjmp.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>

static uint8_t init[8 * 64] __attribute__((aligned(64)));
static uint8_t outv[8 * 64] __attribute__((aligned(64)));
static uint8_t out2[8 * 64 + 64] __attribute__((aligned(64)));
static uint8_t maskbuf[64] __attribute__((aligned(64)));
static uint8_t *page;           /* 2 pages: RW then PROT_NONE */
static long pgsz, vlenb;
static uint64_t h, hall;

static void mix(const void *p, size_t n)
{
    const uint8_t *b = p;
    for (size_t i = 0; i < n; i++) {
        h = (h ^ b[i]) * 0x100000001b3ull;
    }
}

static uint64_t rnd = 0x9e3779b97f4a7c15ull;
static uint64_t next(void)
{
    rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17;
    return rnd;
}
static void fill(uint8_t *p, size_t n)
{
    for (size_t i = 0; i < n; i++) {
        p[i] = next();
    }
}
''')

CLOB = '''"memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13",
                   "v14", "v15"'''

def body(nm, setvl, eew, vm, extra_in):
    return f'''
static long ldff_{nm}(long avl, const void *src)
{{
    long vl;
    asm volatile("vl8re8.v v8, (%[init])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "{setvl}\\n\\t"
                 "vle{eew}ff.v v8, (%[src]){vm}\\n\\t"
                 "csrr %[vl], vl\\n\\t"
                 "vse{eew}.v v8, (%[o2])\\n\\t"
                 "vs8r.v v8, (%[out])\\n\\t"
                 : [vl] "=&r"(vl)
                 : [init] "r"(init), [mb] "r"(maskbuf), {extra_in}
                   [src] "r"(src), [out] "r"(outv), [o2] "r"(out2)
                 : {CLOB});
    return vl;
}}
'''

names = []
for (eew, sew, lname, l, emul) in combos:
    for masked in (0, 1):
        vm = ', v0.t' if masked else ''
        mu = f'e{sew}, {lname}, tu, mu'
        nm = f'e{eew}_s{sew}_{lname}_{"m" if masked else "u"}'
        w(body(nm, f'vsetvli %[vl], %[avl], {mu}', eew, vm, '[avl] "r"(avl),'))
        names.append((nm, eew, sew, l, masked, -1))
        for k in KS:
            nmk = f'i{k}_{nm}'
            w(body(nmk, f'vsetivli %[vl], {k}, {mu}', eew, vm, ''))
            names.append((nmk, eew, sew, l, masked, k))

w('''
typedef long (*tfn)(long, const void *);
struct tcase { const char *name; tfn ld; int eew, sew, lmul, masked, imm; };
static const struct tcase cases[] = {
''')
for (nm, eew, sew, l, masked, k) in names:
    w(f'    {{ "{nm}", ldff_{nm}, {eew}, {sew}, {l}, {masked}, {k} }},\n')
w('''};
#define NCASES (sizeof(cases) / sizeof(cases[0]))

/* strlen as in glibc's RVV version: e8, m8 (or m1), vle8ff.v in a loop */
static long vstrlen_m8(const char *s)
{
    const char *p = s;
    long vl, idx;
    for (;;) {
        asm volatile("vsetvli %[vl], zero, e8, m8, ta, ma\\n\\t"
                     "vle8ff.v v8, (%[p])\\n\\t"
                     "csrr %[vl], vl\\n\\t"
                     "vmseq.vi v0, v8, 0\\n\\t"
                     "vfirst.m %[idx], v0\\n\\t"
                     : [vl] "=&r"(vl), [idx] "=&r"(idx)
                     : [p] "r"(p)
                     : "memory", "v0", "v8", "v9", "v10", "v11", "v12",
                       "v13", "v14", "v15");
        if (idx >= 0) {
            return p + idx - s;
        }
        p += vl;
    }
}

static long vstrlen_m1(const char *s)
{
    const char *p = s;
    long vl, idx;
    for (;;) {
        asm volatile("vsetvli %[vl], zero, e8, m1, ta, ma\\n\\t"
                     "vle8ff.v v8, (%[p])\\n\\t"
                     "csrr %[vl], vl\\n\\t"
                     "vmseq.vi v0, v8, 0\\n\\t"
                     "vfirst.m %[idx], v0\\n\\t"
                     : [vl] "=&r"(vl), [idx] "=&r"(idx)
                     : [p] "r"(p)
                     : "memory", "v0", "v8");
        if (idx >= 0) {
            return p + idx - s;
        }
        p += vl;
    }
}

static sigjmp_buf jb;
static volatile long fault_off;
static void segv(int sig, siginfo_t *si, void *uc)
{
    fault_off = (uint8_t *)si->si_addr - (page + pgsz);
    siglongjmp(jb, 1);
}

static void reset_vstart(void)
{
    asm volatile("csrw vstart, zero" ::: "memory");
}

static void run(const struct tcase *t, long avl, const void *src)
{
    long vl;
    fill(init, sizeof(init));
    fill(out2, sizeof(out2));
    fault_off = -999999;
    if (sigsetjmp(jb, 1) == 0) {
        vl = t->ld(avl, src);
        mix(&vl, sizeof(vl));
        mix(outv, 8 * vlenb);
        mix(out2, sizeof(out2));
    } else {
        reset_vstart();
        mix((const void *)&fault_off, sizeof(fault_off));
    }
}

int main(int argc, char **argv)
{
    uint8_t *buf;
    struct sigaction sa;
    long total = 0;

    asm volatile("csrr %0, vlenb" : "=r"(vlenb));
    pgsz = sysconf(_SC_PAGESIZE);
    page = mmap(NULL, 2 * pgsz, PROT_READ | PROT_WRITE,
                MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    mprotect(page + pgsz, pgsz, PROT_NONE);
    buf = malloc(8 * 64 + 256);
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = segv;
    sa.sa_flags = SA_SIGINFO | SA_NODEFER;
    sigaction(SIGSEGV, &sa, NULL);
    printf("vlenb %ld, %zu cases\\n", vlenb, NCASES);

    for (size_t c = 0; c < NCASES; c++) {
        const struct tcase *t = &cases[c];
        long vlmax = t->lmul >= 0 ? (vlenb * 8 / t->sew) << t->lmul
                                  : (vlenb * 8 / t->sew) >> -t->lmul;
        long vlr = t->imm < 0 ? vlmax : t->imm < vlmax ? t->imm : vlmax;
        long avls[] = { 0, 1, 2, 3, vlmax / 2, vlmax - 1, vlmax, vlmax + 1,
                        1000000 };
        long ebytes = t->eew / 8;

        h = 0xcbf29ce484222325ull;
        /* inside a readable buffer, aligned or not */
        for (int k = 0; k < (t->imm >= 0 ? 1 : 9); k++) {
            for (int misal = 0; misal < 2; misal++) {
                fill(maskbuf, sizeof(maskbuf));
                fill(buf, 8 * 64 + 256);
                run(t, avls[k], buf + 64 + misal * 3);
            }
        }

        memset(page, 0x5a, pgsz);
        fill(page + pgsz - 600, 600);
        /* the elements from j on are in the PROT_NONE page: vl reduced
           to j (j = 0: fault), or none past vl */
        for (long j = 0; j <= vlr && j <= 70; j++) {
            fill(maskbuf, sizeof(maskbuf));
            maskbuf[0] |= 1;
            run(t, vlmax, page + pgsz - j * ebytes);
            if (t->masked) {
                memset(maskbuf, 0xff, sizeof(maskbuf));
                run(t, vlmax, page + pgsz - j * ebytes);
            }
        }
        /* not aligned on the element size, crossing inside an element */
        for (long j = 1; j <= vlr && j <= 20; j++) {
            memset(maskbuf, 0xff, sizeof(maskbuf));
            run(t, vlmax, page + pgsz - j * ebytes + 1);
        }
        /* first element in the PROT_NONE page, vl = 0 (no fault) or not */
        memset(maskbuf, 0xff, sizeof(maskbuf));
        run(t, 0, page + pgsz);
        run(t, 0, page + pgsz + 8);
        run(t, 5, page + pgsz + 8);
        run(t, vlmax, page + pgsz + pgsz / 2);
        /* vl = 0 at a page start */
        run(t, 0, page);
        printf("%-20s %016llx\\n", t->name, (unsigned long long)h);
        hall ^= h + c;
    }

    /* strlen: NUL before the end of the readable page, or at its last byte */
    h = 0xcbf29ce484222325ull;
    for (long len = 0; len < 600; len += len < 80 ? 1 : 37) {
        for (long end = 0; end < 3; end++) {
            char *s = (char *)page + pgsz - 1 - len - end * 97;
            memset(page, 'a', pgsz);
            s[len] = 0;
            long a = vstrlen_m8(s), b = vstrlen_m1(s);
            total += a + b;
            if (a != len || b != len) {
                printf("strlen %ld/%ld: %ld %ld\\n", len, end, a, b);
            }
            mix(&a, sizeof(a));
            mix(&b, sizeof(b));
        }
    }
    printf("strlen %016llx %ld\\n", (unsigned long long)h, total);
    hall ^= h;
    printf("all %016llx\\n", (unsigned long long)hall);
    return 0;
}
''')
open('rvv_ldff.c', 'w').write(''.join(out))
print(len(names), 'cases')
