#!/usr/bin/env python3
# Generates rvsat.c: vsaddu, vsadd, vssubu, vssub (.vv, .vx, .vi) with every
# SEW and LMUL >= 1, vl = VLMAX or not: results and vxsat.
ops = ['vsaddu', 'vsadd', 'vssubu', 'vssub']
out = []
w = out.append
w(r'''/* generated by gen_sat.py */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static uint8_t va[8 * 64] __attribute__((aligned(64))), vb[8 * 64] __attribute__((aligned(64)));
static uint8_t vc[8 * 64] __attribute__((aligned(64))), vo[8 * 64] __attribute__((aligned(64)));
static uint64_t h;
static void mix(const void *p, size_t n) { const uint8_t *b = p; for (size_t i = 0; i < n; i++) h = (h ^ b[i]) * 0x100000001b3ull; }
static uint64_t rnd = 0x9e3779b97f4a7c15ull;
static uint64_t next(void) { rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17; return rnd; }
static void fill(uint8_t *p, size_t n, int sew)
{
    for (size_t i = 0; i < n; i++) p[i] = next();
    /* edge values */
    for (size_t i = 0; i + sew / 8 <= n; i += sew / 8) {
        switch (next() % 6) {
        case 0: memset(p + i, 0xff, sew / 8); break;
        case 1: memset(p + i, 0, sew / 8); break;
        case 2: memset(p + i, 0xff, sew / 8); p[i + sew / 8 - 1] = 0x7f; break;
        case 3: memset(p + i, 0, sew / 8); p[i + sew / 8 - 1] = 0x80; break;
        default: break;
        }
    }
}
''')
tests = []
for op in ops:
    for sew in [8, 16, 32, 64]:
        for lm in ['m1', 'm2', 'm4', 'm8']:
            for form in ['vv', 'vx', 'vi'] if op in ('vsaddu', 'vsadd') else ['vv', 'vx']:
                for vlmode in ['max', 'part']:
                    nm = f'{op}_{form}_e{sew}{lm}_{vlmode}'
                    src = {'vv': 'v24', 'vx': '%[x]', 'vi': '-5'}[form]
                    vset = 'vsetvli %[vl], x0' if vlmode == 'max' else 'vsetvli %[vl], %[avl]'
                    w(f'''static long {nm}(long x, long avl)
{{
    long vl, sat;
    asm volatile("vl8re8.v v8, (%[a])\\n\\t"
                 "vl8re8.v v24, (%[b])\\n\\t"
                 "vl8re8.v v16, (%[c])\\n\\t"
                 "csrwi vxsat, 0\\n\\t"
                 "{vset}, e{sew}, {lm}, tu, mu\\n\\t"
                 "{op}.{form} v16, v8, {src}\\n\\t"
                 "csrr %[sat], vxsat\\n\\t"
                 "vs8r.v v16, (%[o])\\n\\t"
                 : [vl] "=&r"(vl), [sat] "=&r"(sat)
                 : [a] "r"(va), [b] "r"(vb), [c] "r"(vc), [o] "r"(vo), [x] "r"(x), [avl] "r"(avl)
                 : "memory", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15",
                   "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23",
                   "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31");
    return sat * 100000 + vl;
}}
''')
                    tests.append((nm, sew))
w('struct t { const char *n; long (*f)(long, long); int sew; } ts[] = {\n')
for nm, sew in tests:
    w(f'  {{ "{nm}", {nm}, {sew} }},\n')
w(r'''};
int main(void)
{
    long vlenb;
    uint64_t all = 0;
    asm volatile("csrr %0, vlenb" : "=r"(vlenb));
    for (size_t t = 0; t < sizeof(ts) / sizeof(ts[0]); t++) {
        h = 0xcbf29ce484222325ull;
        for (int k = 0; k < 200; k++) {
            long r, x;
            fill(va, sizeof(va), ts[t].sew);
            fill(vb, sizeof(vb), ts[t].sew);
            fill(vc, sizeof(vc), 8);
            x = next();
            if (k & 1) x = (k & 2) ? -1 : 0;
            r = ts[t].f(x, 1 + next() % 300);
            mix(&r, sizeof(r));
            mix(vo, 8 * vlenb);
        }
        printf("%-24s %016llx\n", ts[t].n, (unsigned long long)h);
        all = all * 31 + h;
    }
    printf("all %016llx\n", (unsigned long long)all);
    return 0;
}
''')
open('rvsat.c', 'w').write(''.join(out))
