#!/usr/bin/env python3
# Generates rvmask.c: integer compares (.vv, .vx, .vi, masked or not, vd = vs2
# or v0), mask logical ops, vcpop.m and vfirst.m, with every SEW and LMUL,
# vl = VLMAX, below it, or known (vsetivli).
out = []
w = out.append
w(r'''/* generated by gen_mask.py */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static uint8_t va[8 * 64] __attribute__((aligned(64))), vb[8 * 64] __attribute__((aligned(64)));
static uint8_t vc[8 * 64] __attribute__((aligned(64))), vo[8 * 64] __attribute__((aligned(64)));
static uint8_t mb[64] __attribute__((aligned(64)));
static uint64_t h;
static void mix(const void *p, size_t n) { const uint8_t *b = p; for (size_t i = 0; i < n; i++) h = (h ^ b[i]) * 0x100000001b3ull; }
static uint64_t rnd = 0x9e3779b97f4a7c15ull;
static uint64_t next(void) { rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17; return rnd; }
static void fill(uint8_t *p, size_t n, int sew)
{
    for (size_t i = 0; i < n; i++) p[i] = next();
    for (size_t i = 0; i + sew / 8 <= n; i += sew / 8) {
        switch (next() % 5) {
        case 0: memcpy(p + i, va + i, sew / 8); break;      /* equal to va */
        case 1: memset(p + i, 0xff, sew / 8); break;
        case 2: memset(p + i, 0, sew / 8); break;
        default: break;
        }
    }
}
''')
tests = []
LM = ['mf2', 'm1', 'm2', 'm4', 'm8']
CLOB = '"memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31"'
PRE = '''"vl8re8.v v8, (%[a])\\n\\t"
                 "vl8re8.v v16, (%[b])\\n\\t"
                 "vl8re8.v v24, (%[c])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "vl1re8.v v1, (%[mb2])\\n\\t"'''
def emit(nm, body):
    w(f'''static long {nm}(long x, long avl)
{{
    long vl, r = 0;
    asm volatile({PRE}
                 {body}
                 "vs8r.v v24, (%[o])\\n\\t"
                 "vs1r.v v0, (%[o2])\\n\\t"
                 : [vl] "=&r"(vl), [r] "+&r"(r)
                 : [a] "r"(va), [b] "r"(vb), [c] "r"(vc), [o] "r"(vo), [o2] "r"(vo + 7 * 64), [x] "r"(x),
                   [avl] "r"(avl), [mb] "r"(mb), [mb2] "r"(mb + 32)
                 : {CLOB});
    return vl * 1000003 + r;
}}
''')
    tests.append(nm)
vsets = {'max': 'vsetvli %[vl], x0', 'part': 'vsetvli %[vl], %[avl]', 'imm': 'vsetivli %[vl], 13'}
for sew in [8, 16, 32, 64]:
    for lm in LM:
        if lm == 'mf2' and sew == 64:
            continue
        for vm in ['max', 'part', 'imm']:
            vs = f'"{vsets[vm]}, e{sew}, {lm}, tu, mu\\n\\t"'
            for op in ['vmseq', 'vmsne', 'vmsltu', 'vmslt', 'vmsleu', 'vmsle']:
                for msk in ['', ', v0.t']:
                    emit(f'{op}_vv_e{sew}{lm}_{vm}{"_m" if msk else ""}', vs + f'\n                 "{op}.vv v24, v8, v16{msk}\\n\\t"')
            for op in ['vmseq', 'vmsne', 'vmsltu', 'vmslt', 'vmsleu', 'vmsle', 'vmsgtu', 'vmsgt']:
                emit(f'{op}_vx_e{sew}{lm}_{vm}', vs + f'\n                 "{op}.vx v24, v8, %[x]\\n\\t"')
                emit(f'{op}_vx_e{sew}{lm}_{vm}_m', vs + f'\n                 "{op}.vx v24, v8, %[x], v0.t\\n\\t"')
            for op in ['vmseq', 'vmsne', 'vmsleu', 'vmsle', 'vmsgtu', 'vmsgt']:
                emit(f'{op}_vi_e{sew}{lm}_{vm}', vs + f'\n                 "{op}.vi v24, v8, -3\\n\\t"')
            # vd == vs2 (the first register of its group), and vd == v0 masked
            emit(f'vmseq_vv_vdvs2_e{sew}{lm}_{vm}', vs + '\n                 "vmseq.vv v8, v8, v16\\n\\t"\n                 "vmv1r.v v24, v8\\n\\t"')
            emit(f'vmsltu_vx_vdv0_e{sew}{lm}_{vm}', vs + '\n                 "vmsltu.vx v0, v8, %[x], v0.t\\n\\t"')
            for op in ['vmand', 'vmnand', 'vmandn', 'vmxor', 'vmor', 'vmnor', 'vmorn', 'vmxnor']:
                emit(f'{op}_e{sew}{lm}_{vm}', vs + f'\n                 "{op}.mm v24, v0, v1\\n\\t"')
            emit(f'vmand_vdsrc_e{sew}{lm}_{vm}', vs + '\n                 "vmand.mm v1, v1, v0\\n\\t"\n                 "vmv1r.v v24, v1\\n\\t"')
            for op in ['vcpop.m', 'vfirst.m']:
                emit(f'{op.replace(".", "_")}_e{sew}{lm}_{vm}', vs + f'\n                 "{op} %[r], v1\\n\\t"')
                emit(f'{op.replace(".", "_")}_e{sew}{lm}_{vm}_m', vs + f'\n                 "{op} %[r], v1, v0.t\\n\\t"')
w('struct t { const char *n; long (*f)(long, long); } ts[] = {\n')
for nm in tests:
    w(f'  {{ "{nm}", {nm} }},\n')
w(r'''};
int main(void)
{
    long vlenb;
    uint64_t all = 0;
    asm volatile("csrr %0, vlenb" : "=r"(vlenb));
    for (size_t t = 0; t < sizeof(ts) / sizeof(ts[0]); t++) {
        h = 0xcbf29ce484222325ull;
        for (int k = 0; k < 24; k++) {
            long r;
            fill(va, sizeof(va), 8);
            fill(vb, sizeof(vb), 8 << (k % 4));
            fill(vc, sizeof(vc), 8);
            for (size_t i = 0; i < sizeof(mb); i++) mb[i] = next();
            if (k % 7 == 3) memset(mb + 32, 0, 32);
            r = ts[t].f(k & 1 ? (long)next() : (long)*(int64_t *)(va + 8 * (k % 8)), k < 12 ? k * 3 : next() % 600);
            mix(&r, sizeof(r));
            mix(vo, 8 * vlenb);
        }
        printf("%-30s %016llx\n", ts[t].n, (unsigned long long)h);
        all = all * 31 + h;
    }
    printf("all %016llx\n", (unsigned long long)all);
    return 0;
}
''')
open('rvmask.c', 'w').write(''.join(out))
