#!/usr/bin/env python3
# Generates rvvfp.c: RVV floating point (vfadd... vfnmsub, vfmin/vfmax,
# vfsqrt), SEW 32 and 64, every LMUL, vl = VLMAX or not, masked or not,
# frm RNE or not: results and fflags.
out = []
w = out.append
w(r'''/* generated by gen_vfp.py */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static uint8_t va[8 * 64] __attribute__((aligned(64))), vb[8 * 64] __attribute__((aligned(64)));
static uint8_t vc[8 * 64] __attribute__((aligned(64))), vo[8 * 64] __attribute__((aligned(64)));
static uint8_t mb[64] __attribute__((aligned(64)));
static uint64_t h;
static void mix(const void *p, size_t n) { const uint8_t *b = p; for (size_t i = 0; i < n; i++) h = (h ^ b[i]) * 0x100000001b3ull; }
static uint64_t rnd = 0x9e3779b97f4a7c15ull;
static uint64_t next(void) { rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17; return rnd; }
static const uint64_t dsp[] = {
    0, 0x8000000000000000ull, 0x3ff0000000000000ull, 0xbff0000000000000ull,
    0x7ff0000000000000ull, 0xfff0000000000000ull, 0x7ff8000000000000ull,
    0x7ff0000000000001ull, 0xfff4000000000123ull, 0x0000000000000001ull,
    0x0010000000000000ull, 0x7fefffffffffffffull, 0x4000000000000000ull,
    0x3fe0000000000000ull, 0x000fffffffffffffull, 0x3ca0000000000000ull,
};
static const uint32_t ssp[] = {
    0, 0x80000000, 0x3f800000, 0xbf800000, 0x7f800000, 0xff800000, 0x7fc00000,
    0x7f800001, 0xffa00123, 0x00000001, 0x00800000, 0x7f7fffff, 0x40000000,
    0x3f000000, 0x007fffff, 0x33800000,
};
static void fill(uint8_t *p, size_t n, int sew)
{
    for (size_t i = 0; i < n; i += sew / 8) {
        uint64_t v;
        switch (next() % 4) {
        case 0:
            v = sew == 64 ? dsp[next() % 16] : ssp[next() % 16];
            break;
        case 1:
            v = sew == 64 ? (next() & 0x800fffffffffffffull) | (0x3fcull + next() % 8) << 52
                          : ((uint32_t)next() & 0x807fffff) | (uint32_t)(0x7c + next() % 8) << 23;
            break;
        default:
            v = next();
            break;
        }
        memcpy(p + i, &v, sew / 8);
    }
}
''')
tests = []
OPS2 = ['vfadd', 'vfsub', 'vfmul', 'vfdiv', 'vfmin', 'vfmax']
OPSF = ['vfrsub', 'vfrdiv']
OPS3 = ['vfmacc', 'vfnmacc', 'vfmsac', 'vfnmsac', 'vfmadd', 'vfnmadd', 'vfmsub', 'vfnmsub']
CLOB = '"memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31", "fa0"'
def emit(nm, insn, vset):
    w(f'''static long {nm}(long fbits, long avl, long frm)
{{
    long vl, fl;
    asm volatile("vl8re8.v v8, (%[a])\\n\\t"
                 "vl8re8.v v16, (%[b])\\n\\t"
                 "vl8re8.v v24, (%[c])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "fmv.d.x fa0, %[f]\\n\\t"
                 "fsrm %[frm]\\n\\t"
                 "{vset}\\n\\t"
                 "fsflags zero\\n\\t"
                 "{insn}\\n\\t"
                 "frflags %[fl]\\n\\t"
                 "fsrm zero\\n\\t"
                 "vs8r.v v24, (%[o])\\n\\t"
                 : [vl] "=&r"(vl), [fl] "=&r"(fl)
                 : [a] "r"(va), [b] "r"(vb), [c] "r"(vc), [o] "r"(vo), [f] "r"(fbits),
                   [avl] "r"(avl), [mb] "r"(mb), [frm] "r"(frm)
                 : {CLOB});
    return vl * 1000 + fl;
}}
''')
    tests.append(nm)
for sew in [32, 64]:
    for lm in ['mf2', 'm1', 'm2', 'm4', 'm8']:
        if lm == 'mf2' and sew == 64:
            continue
        for vm in ['max', 'part']:
            vset = f'vsetvli %[vl], x0, e{sew}, {lm}, tu, mu' if vm == 'max' else f'vsetvli %[vl], %[avl], e{sew}, {lm}, tu, mu'
            for op in OPS2:
                emit(f'{op}_vv_e{sew}{lm}_{vm}', f'{op}.vv v24, v8, v16', vset)
                emit(f'{op}_vf_e{sew}{lm}_{vm}', f'{op}.vf v24, v8, fa0', vset)
                emit(f'{op}_vv_e{sew}{lm}_{vm}_m', f'{op}.vv v24, v8, v16, v0.t', vset)
            for op in OPSF:
                emit(f'{op}_vf_e{sew}{lm}_{vm}', f'{op}.vf v24, v8, fa0', vset)
            for op in OPS3:
                emit(f'{op}_vv_e{sew}{lm}_{vm}', f'{op}.vv v24, v8, v16', vset)
                emit(f'{op}_vf_e{sew}{lm}_{vm}', f'{op}.vf v24, fa0, v16', vset)
            emit(f'vfsqrt_v_e{sew}{lm}_{vm}', 'vfsqrt.v v24, v8', vset)
            emit(f'vfadd_vv_same_e{sew}{lm}_{vm}', 'vfadd.vv v24, v24, v24', vset)
w('struct t { const char *n; long (*f)(long, long, long); int sew; } ts[] = {\n')
for nm in tests:
    w(f'  {{ "{nm}", {nm}, {32 if "e32" in nm else 64} }},\n')
w(r'''};
int main(void)
{
    long vlenb;
    uint64_t all = 0;
    asm volatile("csrr %0, vlenb" : "=r"(vlenb));
    for (size_t t = 0; t < sizeof(ts) / sizeof(ts[0]); t++) {
        h = 0xcbf29ce484222325ull;
        for (int k = 0; k < 40; k++) {
            long r;
            uint64_t f;
            fill(va, sizeof(va), ts[t].sew);
            fill(vb, sizeof(vb), ts[t].sew);
            fill(vc, sizeof(vc), ts[t].sew);
            for (size_t i = 0; i < sizeof(mb); i++) mb[i] = next();
            f = ts[t].sew == 64 ? dsp[k % 16] : (0xffffffff00000000ull | ssp[k % 16]);
            if (k % 13 == 7) f = next();          /* not NaN-boxed */
            r = ts[t].f(f, k < 20 ? k : next() % 300, k % 9 == 4 ? 2 : k % 9 == 5 ? 1 : 0);
            mix(&r, sizeof(r));
            mix(vo, 8 * vlenb);
        }
        printf("%-28s %016llx\n", ts[t].n, (unsigned long long)h);
        all = all * 31 + h;
    }
    printf("all %016llx\n", (unsigned long long)all);
    return 0;
}
''')
open('rvvfp.c', 'w').write(''.join(out))
