#!/usr/bin/env python3
# Generates rvmv.c: vmv.v.x, vmv.v.i, vid.v (also masked) with every SEW
# and LMUL, vl = VLMAX, below it, or known (vsetivli).
out = []
w = out.append
w(r'''/* generated by gen_mv.py */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static uint8_t vc[8 * 64] __attribute__((aligned(64))), vo[8 * 64] __attribute__((aligned(64)));
static uint8_t mb[64] __attribute__((aligned(64)));
static uint64_t h;
static void mix(const void *p, size_t n) { const uint8_t *b = p; for (size_t i = 0; i < n; i++) h = (h ^ b[i]) * 0x100000001b3ull; }
static uint64_t rnd = 0x9e3779b97f4a7c15ull;
static uint64_t next(void) { rnd ^= rnd << 13; rnd ^= rnd >> 7; rnd ^= rnd << 17; return rnd; }
''')
tests = []
LM = ['mf8', 'mf4', 'mf2', 'm1', 'm2', 'm4', 'm8']
for op in ['vmv.v.x', 'vmv.v.i', 'vid.v', 'vid.v_m']:
    for sew in [8, 16, 32, 64]:
        for lm in LM:
            if lm.startswith('mf') and sew > 64 // int(lm[2:]):
                continue
            for vlmode in ['max', 'part', 'imm']:
                nm = f'{op.replace(".", "_")}_e{sew}{lm}_{vlmode}'
                vset = {'max': 'vsetvli %[vl], x0', 'part': 'vsetvli %[vl], %[avl]', 'imm': 'vsetivli %[vl], 7'}[vlmode]
                insn = {'vmv.v.x': 'vmv.v.x v8, %[x]', 'vmv.v.i': 'vmv.v.i v8, -11', 'vid.v': 'vid.v v8', 'vid.v_m': 'vid.v v8, v0.t'}[op]
                w(f'''static long {nm}(long x, long avl)
{{
    long vl;
    asm volatile("vl8re8.v v8, (%[c])\\n\\t"
                 "vl1re8.v v0, (%[mb])\\n\\t"
                 "{vset}, e{sew}, {lm}, tu, mu\\n\\t"
                 "{insn}\\n\\t"
                 "vs8r.v v8, (%[o])\\n\\t"
                 : [vl] "=&r"(vl)
                 : [c] "r"(vc), [o] "r"(vo), [x] "r"(x), [avl] "r"(avl), [mb] "r"(mb)
                 : "memory", "v0", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15");
    return vl;
}}
''')
                tests.append(nm)
w('struct t { const char *n; long (*f)(long, long); } ts[] = {\n')
for nm in tests:
    w(f'  {{ "{nm}", {nm} }},\n')
w(r'''};
int main(void)
{
    long vlenb;
    uint64_t all = 0;
    asm volatile("csrr %0, vlenb" : "=r"(vlenb));
    for (size_t t = 0; t < sizeof(ts) / sizeof(ts[0]); t++) {
        h = 0xcbf29ce484222325ull;
        for (int k = 0; k < 64; k++) {
            long r;
            for (size_t i = 0; i < sizeof(vc); i++) vc[i] = next();
            for (size_t i = 0; i < sizeof(mb); i++) mb[i] = next();
            r = ts[t].f(next(), k < 40 ? k : next() % 300);
            mix(&r, sizeof(r));
            mix(vo, 8 * vlenb);
        }
        printf("%-24s %016llx\n", ts[t].n, (unsigned long long)h);
        all = all * 31 + h;
    }
    printf("all %016llx\n", (unsigned long long)all);
    return 0;
}
''')
open('rvmv.c', 'w').write(''.join(out))
